# Last modified 16.07.2021 15:01 (GMT+4)
image: registry.gitlab.com/xpac-group/sysadmin/docker/images/wordpress-ci

stages:
  - build
  - deploy

# Copy our private SSH key and known hosts keys into place for SFTP deployments
before_script:
  - mkdir ~/.ssh
  - echo $SSH_PRIVATE_KEY | base64 -d >~/.ssh/id_rsa && chmod 400 ~/.ssh/id_rsa
  - echo $SSH_PUBLIC_KEY | base64 -d >~/.ssh/id_rsa.pub
  - echo $SSH_KNOWN_HOSTS | base64 -d >~/.ssh/known_hosts && chmod 0644 ~/.ssh/known_hosts
  - composer global config gitlab-token.gitlab.com $GITLAB_READ_ACCESS_TOKEN

build:
  stage: build
  script:
    - wp-build
  artifacts:
    paths:
      - ./
    reports:
      dotenv: build.env

xpac:dev:
  stage: deploy
  only:
    - develop
  script:
    - wp-deploy plugin 188.34.206.116 2022
  dependencies:
    - build

nebeauty:prod:
  stage: deploy
  only:
    - master
  script:
    - wp-deploy plugin 65.21.252.203 7022
  dependencies:
    - build

nebeauty:dev:
  stage: deploy
  only:
    - develop
  script:
    - wp-deploy plugin 65.21.252.203 2322
  dependencies:
    - build

noorb:dev:
  stage: deploy
  only:
    - develop
  script:
    - wp-deploy plugin 188.34.206.116 23122
  dependencies:
    - build

novembit:dev:
  stage: deploy
  only:
    - develop
  script:
    - wp-deploy plugin 188.34.206.116 2822
  dependencies:
    - build

backend:
  stage: deploy
  only:
    - develop
  script:
    - wp-deploy plugin 188.34.206.116 2422 # backend
  dependencies:
    - build

frontend:
  stage: deploy
  only:
    - develop
  script:
    - wp-deploy plugin 188.34.206.116 2522 # frontend
  dependencies:
    - build

etadevosyan:
  stage: deploy
  only:
    - develop
  script:
    - wp-deploy plugin 188.34.206.116 2622 # erik
  dependencies:
    - build

ayordanyan:
  stage: deploy
  only:
    - develop
  script:
    - wp-deploy plugin 188.34.206.116 2722 # aaron
  dependencies:
    - build

i18n:
  stage: deploy
  only:
    - develop
  script:
    - wp-deploy plugin 188.34.206.116 3022 # i18n
  dependencies:
    - build

aalayan:
  stage: deploy
  only:
    - develop
  script:
    - wp-deploy plugin 188.34.206.116 21022 # ani
  dependencies:
    - build
