# Last modified 16.07.2021 15:01 (GMT+4)
image: registry.gitlab.com/xpac-group/sysadmin/docker/images/wordpress-ci

stages:
  - build
  - deploy

# Copy our private SSH key and known hosts keys into place for SFTP deployments
before_script:
  - mkdir ~/.ssh
  - echo $SSH_PRIVATE_KEY | base64 -d >~/.ssh/id_rsa && chmod 400 ~/.ssh/id_rsa
  - echo $SSH_PUBLIC_KEY | base64 -d >~/.ssh/id_rsa.pub
  - echo $SSH_KNOWN_HOSTS | base64 -d >~/.ssh/known_hosts && chmod 0644 ~/.ssh/known_hosts
  - composer global config gitlab-token.gitlab.com $GITLAB_READ_ACCESS_TOKEN
  - function dp { ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p $2 root@$1 "cd /var/www/html; wp plugin install 'https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/jobs/$BUILD_JOB_ID/artifacts/$CI_PROJECT_NAME.zip?private_token=$GITLAB_READ_ACCESS_TOKEN' --force"; }

build:
  stage: build
  script:
    - wp-build $CI_PROJECT_NAME
    - echo "BUILD_JOB_ID=$CI_JOB_ID" >> build.env
  artifacts:
    paths:
      - ./
    reports:
      dotenv: build.env

xpac:dev:
  stage: deploy
  only:
    - develop
  script:
    - dp 188.34.206.116 2022 develop
  dependencies:
    - build

nebeauty:prod:
  stage: deploy
  only:
    - master
  script:
    - dp 65.21.252.203 7022 develop
  dependencies:
    - build

nebeauty:dev:
  stage: deploy
  only:
    - develop
  script:
    - dp 65.21.252.203 2322 develop
  dependencies:
    - build

noorb:dev:
  stage: deploy
  only:
    - develop
  script:
    - dp 188.34.206.116 23122 develop
  dependencies:
    - build

novembit:dev:
  stage: deploy
  only:
    - develop
  script:
    - dp 188.34.206.116 2822 develop
  dependencies:
    - build

backend:
  stage: deploy
  only:
    - develop
  script:
    - dp 188.34.206.116 2422 develop # backend
  dependencies:
    - build

frontend:
  stage: deploy
  only:
    - develop
  script:
    - dp 188.34.206.116 2522 develop # frontend
  dependencies:
    - build

etadevosyan:
  stage: deploy
  only:
    - develop
  script:
    - dp 188.34.206.116 2622 develop # erik
  dependencies:
    - build

ayordanyan:
  stage: deploy
  only:
    - develop
  script:
    - dp 188.34.206.116 2722 develop # aaron
  dependencies:
    - build

i18n:
  stage: deploy
  only:
    - develop
  script:
    - dp 188.34.206.116 3022 develop # i18n
  dependencies:
    - build

aalayan:
  stage: deploy
  only:
    - develop
  script:
    - dp 188.34.206.116 21022 develop # ani
  dependencies:
    - build
