image: registry.gitlab.com/xpac-group/sysadmin/xpac-hub:wp-gitlab-ci-builder

stages:
  - build
  - deploy

# Copy our private SSH key and known hosts keys into place for SFTP deployments
before_script:
  - mkdir ~/.ssh
  - echo $SSH_PRIVATE_KEY | base64 -d >~/.ssh/id_rsa && chmod 400 ~/.ssh/id_rsa
  - echo $SSH_PUBLIC_KEY | base64 -d >~/.ssh/id_rsa.pub
  - echo $SSH_KNOWN_HOSTS | base64 -d >~/.ssh/known_hosts && chmod 0644 ~/.ssh/known_hosts
  - composer global config gitlab-token.gitlab.com $GITLAB_READ_ACCESS_TOKEN

build:
  stage: build
  script:
    - wp-build
  artifacts:
    paths:
      - ./
    reports:
      dotenv: build.env

deploy:dev:
  stage: deploy
  only:
    - develop
  script: # CI_PROJECT_NAME
    - curl -X POST -F token=$CI_JOB_TOKEN -F "ref=master" -F "variables[UPDATE_WP_COMPONENT]=true" -F "variables[STACK]=xpac-saas" -F "variables[UPSTREAM_CI_COMMIT_BRANCH]=$CI_COMMIT_BRANCH" -F "variables[UPSTREAM_CI_PROJECT_NAME]=$CI_PROJECT_NAME" -F "variables[UPSTREAM_CI_PROJECT_ID]=$CI_PROJECT_ID" https://gitlab.com/api/v4/projects/26615628/trigger/pipeline
  dependencies:
    - build

deploy:prod:
  stage: deploy
  only:
    - master
  script: # CI_PROJECT_NAME
    - curl -X POST -F token=$CI_JOB_TOKEN -F "ref=master" -F "variables[UPDATE_WP_COMPONENT]=true" -F "variables[STACK]=xpac-saas" -F "variables[UPSTREAM_CI_COMMIT_BRANCH]=$CI_COMMIT_BRANCH" -F "variables[UPSTREAM_CI_PROJECT_NAME]=$CI_PROJECT_NAME" -F "variables[UPSTREAM_CI_PROJECT_ID]=$CI_PROJECT_ID" https://gitlab.com/api/v4/projects/26615628/trigger/pipeline
  dependencies:
    - build
