stages:
  - build
  - deploy

# The Docker image we use that contains our custom CI scripts
image: registry.gitlab.com/xpac-group/sysadmin/docker/images/wordpress-php7.4-ci-cd:latest

# Copy our private SSH key and known hosts keys into place for SFTP deployments
before_script:
  - mkdir ~/.ssh
  - echo $XPAC_PRIVATE_KEY | base64 -d >~/.ssh/id_rsa && chmod 400 ~/.ssh/id_rsa
  - echo $XPAC_PUBLIC_KEY | base64 -d >~/.ssh/id_rsa.pub
  - composer global config gitlab-token.gitlab.com $XPAC_GITLAB_GROUP_TOKEN
  - RPATH=/var/www/html/wp-content/plugins
  - FILE="${CI_PROJECT_NAME}.tar.gz"
  - function upload { scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P $2 $FILE root@$1:$RPATH/$FILE; }
  - function extract { ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p $2 root@$1 "cd ${RPATH} && rm -rf ${CI_PROJECT_NAME} && mkdir -p ${CI_PROJECT_NAME} && tar -xzf $FILE -C ./${CI_PROJECT_NAME} && rm -rf ./$FILE;"; }
  - function deploy { upload "$1" "$2" && extract "$1" "$2"; }

build:
  stage: build
  script:
    - composer update
    - rm -rf node_modules
    - touch $FILE
    - tar --exclude="./${FILE}" -czf  ${FILE} ./
  artifacts:
    paths:
      - '*.tar.gz'

deploy:dev:
  stage: deploy
  only:
    - develop
  script:
    - deploy "$XPAC_DEV_SERVER_HOST" "$XPAC_DEV_SERVER_PORT"

deploy:novembit:
  stage: deploy
  only:
    - develop
  script:
    - deploy "$XPAC_NOVEMBIT_SERVER_HOST" "$XPAC_NOVEMBIT_SERVER_PORT"
